### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by Shane-XB-Qian** [simonwalz/screen-save#5]
part of generated .screenrc-testsess is something like this:
```screen
chdir "/home/shane/foo/screen-save"
at "0#" exec !.! sh -c "sleep 0.2;echo '.........a_long_text_chars.........'|base64 -d|gzip -cd;echo -n 'vim screen-save\\n' >&2"
```

1, seems would not correctly open `vim screen-save` if Not "cd /home/shane/foo/screen-save" first before `screen -c .screenrc-testsess`.
2, if self .screenrc had some e.g `screen -t foo` and `screen -t bar`, then the window opened incorrectly, it would not check how many or was there same title window existed first.
3, when `screen -c .screenrc-testsess` init it, the message prompt: missing `'` quote. for now did not find where is it.

**Comment by simonwalz** [comment]
To 1:

The first line "chdir ..." shall change the directory, so that the following line creates a shell in that window.
See https://github.com/simonwalz/screen-save/blob/master/screen-save#L235

The following test code shall open to windows, one in directory /tmp and one in directory /home
```screenrc
chdir "/tmp"
screen -t shell         0
chdir "/home"
screen -t shell         1
```

Does this work?

Is it possible that you have a directory change in your bashrc / zshrc / .. file?


To 2:
At the moment in https://github.com/simonwalz/screen-save/blob/master/screen-save#L157
```bash
write "source \"${HOME}/.screenrc\""
```
I include the .screenrc file. You your case you defined extra windows there. I will think about it, pasting the contents of the file insteed and remove all window definition lines.

To 3:
I think I saw this as well, but have not traced it yet. Could you provide a sample file?

**Comment by Shane-XB-Qian** [comment]
To 3:
```screen
source "/home/shane/.screenrc"

sessionname "testsess"

screen -t "foo" 0
at "0#" exec !.! sh -c "sleep 0.2;echo 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\noooooooooooooooooooooooooooooooooooooooooooooooooooooooo';"
```

i tried to minimal the sample, IF removed most `ooo` (e.g only left one `o`), then no `missing ' qoute` message.
// maybe related to length limitation?

**Comment by Shane-XB-Qian** [comment]
To 1 and 2:
those two are related: 
a) if previous screen cmd failed (e.g such `missing ' quote`), then looks would no further `vim foo` cmd were executed;
b) if there windows creation in self `.screenrc`, then `screen -t 'foo' 0` and `at "0#"` exec some_cmd` would run at wrong window (then `chdir` looks was to wrong window too if so)

-------------------

c) actually, directly `vim foo` to vim to save/restore `vim session` perhaps was not a good idea, since vim perhaps opened many files at different folders, it probably did not open them all with abs-path, Or to vim, probably can use vim session itself (check `:h mksession` in vim) instead, otherwise looks it's difficult to make it correct (unless give up to restore vim session).

**Comment by simonwalz** [comment]
To 3:

You are right. The input buffer of screen when reading its screenrc files is exactly 2048 (like in your example). See https://github.com/shyouhei/screen/blob/5c1b062475ea5324cec2d81d5687f9b9d1125990/src/fileio.c#L180

I found a possibility to suppress the error message, but not a way to overcome the issue.

Is it common that you have lines longer than 2048? Or can we just ignore these cases?

**Comment by simonwalz** [comment]
To 1+2 (a) + (b)
I have removed the source command from ~/.screenrc. Instead, I copy the relevant commands directly from the file.
I also reduced the line length by removing some characters.

See pull request #7 // or better master branch (I already included it)

Re 1+2 (c)
I will think about it. In the meantime, you can just delete the vim command from the ALLOWED_PROCESSES variable in line 7. This will cause vim commands not to be executed automatically.

**Comment by Shane-XB-Qian** [comment]
> Is it common that you have lines longer than 2048?

actually, i tried to decode that encoded chars, but failed, err was 'incorrect input'.
// maybe needed to pre-process something first.

i think it is common, or is that possible/ok to write that to a tmp file & then decode from that?

-- 
shane.xb.qian

**Comment by Shane-XB-Qian** [comment]
> To 1+2 (a) + (b)
> I removed the source command of ~/.screenrc. Instead I copy relevant commands directly from the file.

thanks, i checked the change, you filtered (just allowed) some screen cmd from .screenrc to that saved sess fs.

> To 1+2 (c)
> I will think about this. At the mean time you can just erase the vim command from the variable `ALLOWED_PROCESSES` in Line 7. This results in not executing vim commands automatically.

ok, thanks. for now this should be ok, or even just to save 'hardcopy', 
but future if this can work with 'vim mksession' then a bit more near 'perfect' to recover sess from crash/reboot. :-)

-- 
shane.xb.qian

**Comment by Shane-XB-Qian** [comment]
> To 1+2 (b)
> I removed the source command of ~/.screenrc. Instead I copy relevant commands directly from the file.
> 
> See Pull Request #7 

thanks, i checked the change, you filtered (just allowed) some screen cmd from .screenrc to that saved sess fs.

> To 1+2 (c)
> I will think about this. At the mean time you can just erase the vim command from the variable `ALLOWED_PROCESSES` in Line 7. This results in not executing vim commands automatically.

ok, thanks. for now this should be ok, or even just to save 'hardcopy', 
but future if this can work with 'vim mksession' then a bit more near 'perfect' to recover sess from crash/reboot. :-)

-- 
shane.xb.qian

**Comment by Shane-XB-Qian** [comment]
closing.. should be ok for now. thx.
