### ISSUE TITLE
group

### ISSUE THREAD

**Issue by 3d7l** [simonwalz/screen-save#8]
Thanks for this tool.

One question: does it also save/restore "group" window or only regular window ?

**Comment by simonwalz** [comment]
This tool just saves the windows (and not the layout or any split settings).

I think you can setup these options globally in your `~/.screenrc` file, but I have not really tested this.

Sample file:

```shell
# cat ~/.screenrc
startup_message off
defutf8 on

# split in four zones and show windows 1 - 4:
split
select 1
split -v
focus next
select 2
focus next
select 3
split -v
focus next
select 4
```

Does this help you?

**Comment by 3d7l** [comment]
Thanks for your answer.

I was thinking about the logical "group" feature,
the one you start with this command:
`screen //group`
I think the feature was introduced in version 4.2.0
(from https://fossies.org/linux/screen/ChangeLog)

Regarding persisting the layout,
your example is very useful.
It is indeed the best way to go.

Thanks

**Comment by simonwalz** [comment]
Okay. Cool feature. I was not aware of that.
The current implementation does not restore these groups.

An implementation might be hard, because the group command can not be queried via the screen command:

```
> screen -S 7151 -p 1 -Q group                                   ~ 
group command cannot be queried.
```

**Comment by 3d7l** [comment]
Thanks for your explanation.

The windows *inside* a group window are saved, which is the most important
(group aggregations can then be re-created with a few keystrokes).
