### ISSUE TITLE
clutter

### ISSUE THREAD

**Issue by lskatz** [simonwalz/screen-save#9]
Hi, I was wondering if it could be reconfigured to save to a subfolder, e.g., `$HOME/.screen-save/`?

**Comment by simonwalz** [comment]
Sure.

I adapted to source code.

Now you can define in your `.bashrc`, `.zshrc`, ... the path that should pre prepended:
```shell
export SCREEN_SAVE_DIR="${HOME}/.screen-save/"
```

The default is still:
```shell
export SCREEN_SAVE_DIR="${HOME}/.screenrc-"
```

**Comment by simonwalz** [comment]
Does this help you? Can we close this issue?
